service: algo-social-api

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

custom:
  path: social
  version: ${opt:version, 'api/v1'}
  environment: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: 4001
  webpack:
    includeModules: true
    isLocal: false
  optimize:
    external: ["swagger-ui-dist"]
    

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment: ${file(config/env.yaml):${self:custom.environment}}
package:
  include: config/*.yaml

functions:
  main:
    handler: src/handler/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          cors: true
          method: post
          path: ${self:custom.path}/user/create
      - http:
          cors: true
          method: get
          path: ${self:custom.path}/user/getByAccountAddress        
      - http:
          cors: true
          method: post
          path: ${self:custom.path}/post/create
      - http:
          cors: true
          method: post
          path: ${self:custom.path}/post/transferAsset
      - http:
          cors: true
          method: get
          path: ${self:custom.path}/post/all
      - http:
          cors: true
          method: get
          path: ${self:custom.path}/post/checkUserPosted
      - http:
          cors: true
          method: get
          path: ${self:custom.path}/post/checkUserPosted                  
