import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import { loggedStateAtom } from "../atoms/loggedState.atom";
import LoadingScreen from "../components/common/LoadingScreen";
import { getUserByAddress } from "../services/API/user";
import styles from "../styles/Home.module.css";
import Login from "./Login";

const Home: NextPage = () => {
  const router = useRouter();
  const [loggedUser, setLoggedState] = useRecoilState(loggedStateAtom);
  const [isLoading, setLoading] = useState(true);

  useEffect(() => {
    getAccount();
  }, []);

  const getAccount = () => {
    const AlgoSigner = window.AlgoSigner;
    if (typeof AlgoSigner !== "undefined") {
      AlgoSigner.accounts({
        ledger: "TestNet",
      })
        .then(async (d: any) => {
          const address = d[0].address;
          const res = await getUserByAddress(address);
          if (res) {
            if (res.data.status === 200) {
              setLoggedState({
                address: address,
                username: res.data.result.username,
              });
              setLoading(false);
              router.push("/Feed");
            } else {
              setLoading(false);
              router.push("/Login");
            }
          }
        })
        .catch((e: any) => {
          console.debug(e);
          setLoading(false);
          router.push("/Login");
        });
    } else {
      setLoading(false);
      router.push("/Login");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>AlgoSocial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading && <LoadingScreen />}
      {!isLoading && <Login />}
    </div>
  );
};

export default Home;
